global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:

- job_name: usersmanager
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - usersmanager:8080

- job_name: gettimeseries
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - gettimeseries:8080

- job_name: kafka
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /
  scheme: http
  static_configs:
  - targets:
    - kafka-exporter:9999